#### This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np
arr1 = np.empty((2,3))
arr2 = np.array([[10,2,3],[23,45,67]])
print (arr2)
arr3 = np.ones ((2,3))
print (arr3)
Arr4 = np.zeros((2,3),dtype=int)
print (Arr4)

[[10  2  3]
 [23 45 67]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]


In [2]:
np.random.random((2,2))

array([[0.202316  , 0.44229407],
       [0.9654521 , 0.69964822]])

In [3]:
var2= np.empty(4)
var2[0] = 5.67
var2[1] =2
var2[2] = 56
var2[3] = 304
print (var2)

[  5.67   2.    56.   304.  ]


In [4]:
print (var2.shape)

(4,)


In [5]:
var3 = np.empty((2,3))
var3[0][0] = 5.67
var3[0][1] = 2
var3[0][2] = 56
var3[1][0] = .09
var3[1][1] = 132
var3[1][2] = 1056
print(var3)
print(var3.shape)

[[5.670e+00 2.000e+00 5.600e+01]
 [9.000e-02 1.320e+02 1.056e+03]]
(2, 3)


In [6]:
var3 = np.empty((2,3), dtype=int)
var3[0][0] = 5.67
var3[0][1] = 2
var3[0][2] = 56
var3[1][0] = .09
var3[1][1] = 132
var3[1][2] = 1056
print (var3)

[[   5    2   56]
 [   0  132 1056]]


In [7]:
print(var3[1])

[   0  132 1056]


In [8]:
print(var3[[0, 1]])

[[   5    2   56]
 [   0  132 1056]]


In [9]:
print(var3[:, 2])

[  56 1056]


In [10]:
print(var3[1][2])

1056


In [11]:
print(var3[:, [1, 2]])

[[   2   56]
 [ 132 1056]]


In [12]:
print(np.transpose(var3))

[[   5    0]
 [   2  132]
 [  56 1056]]


In [13]:
print(var3.reshape(3,2))


[[   5    2]
 [  56    0]
 [ 132 1056]]


In [14]:
arr4= np.empty((2,3), dtype=int)
arr4[0][0] = 5.67
arr4[0][1] = 2
arr4[0][2] = 56
arr4[1][0] = .09
arr4[1][1] = 132
arr4[1][2] = 1056
print (arr4)

[[   5    2   56]
 [   0  132 1056]]


In [15]:
arr5 = np.empty((1,3), dtype=int)
arr5[0][0] = 37
arr5[0][1] = 2.193
arr5[0][2] = 5609
print (arr5)

[[  37    2 5609]]


In [16]:
arr_concat = np.concatenate((arr4, arr5), axis = 0)
print(arr_concat)

[[   5    2   56]
 [   0  132 1056]
 [  37    2 5609]]


In [17]:
var2.min()

2.0

In [18]:
var2.max()

304.0

In [19]:
var2.cumsum()

array([  5.67,   7.67,  63.67, 367.67])

In [20]:
var2.mean()

91.9175

In [21]:
var2.std()

124.2908299865682